### ISSUE TITLE
Very hard to read the source code in a single file

### ISSUE THREAD

**Issue by Abdulmanan0315** [alexantr/filemanager#11]
Hi alexantr ,
This file manager script is the best script ever made i have used many file managers but it is perhaps the most powerful and complete script but there is a little problem it is very hard to read the source in a single .php file .It would be a lot easier if you can make files separate(organize) and a index.php in the root so me and other users would be able to get a lot better learning experience.
Again thank you very much for this script.

**Comment by alexantr** [comment]
The advantage of this file manager is "all in one file".
I have no time to create bulder to build project from separate files now.
You can manually split file to `config`, `actions`, `main`, `functions`, `templates`, `translations`, for exmple.
Just look for comments in source code.

**Comment by Abdulmanan0315** [comment]
thanks for your response i am now trying to split them and they are working perfectly!

**Comment by C-Duv** [comment]
One solution is to use a [Phar](http://php.net/manual/intro.phar.php).
@alexantr Would you accept a PR that split the various parts (configuration, bootstrap, functions/classes and actions)?

**Comment by alexantr** [comment]
Not right now.
