### ISSUE TITLE
Script allows read-only users to read credentials of other users

### ISSUE THREAD

**Issue by C-Duv** [alexantr/filemanager#12]
Because the script allow opening/viewing itself, if the script is located in `$root_path` a read only user can read credentials of others users (in `$auth_users` configuration variable) and then gain write access.

Proposition: add an option to disallow the script to view itself.

**Comment by alexantr** [comment]
This filemanager was created as developer tool. And I'm planning to remove some features which not usable for me as developer: hiding hidden files, readonly users etc. 
Please use [elFinder](https://studio-42.github.io/elFinder/) if you want to give access to unreliable users. Or fork this repo and create new features.

**Comment by alexantr** [comment]
Sorry, but I removed supporting read-only users and hidding hidden files.

Please try [tinyfilemanager](https://github.com/prasathmani/tinyfilemanager)
