### ISSUE TITLE
How to edit files?

### ISSUE THREAD

**Issue by anephew** [alexantr/filemanager#14]
How to edit files?

thank you

**Comment by alexantr** [comment]
1. Download file from server.
2. Edit it by any own editor.
3. Upload it to server.

**Comment by prasathmani** [comment]
I've created updated version of tinyfilemanager with advanced edit feature, have look -
 [tinyfilemanager](https://github.com/prasathmani/tinyfilemanager)

**Comment by alexantr** [comment]
@prasathmani Great! Added link to README.

**Comment by alexantr** [comment]
@anephew Please use [tinyfilemanager](https://github.com/prasathmani/tinyfilemanager)
