### ISSUE TITLE
[security] md5 is horrible for passwords, use something else.

### ISSUE THREAD

**Issue by divinity76** [alexantr/filemanager#15]
like bcrypt. use bcrypt. if for whatever reason, a hacker is able to extract the md5 hash, reversing a plain unsalted MD5 is usually very easy. (also, the password comparison used now is vulnerable to a timing attack, actually allowing hackers to extract the hash, byte-by-byte, but that's for another bugreport...)

**Comment by alexantr** [comment]
Sorry, but password hashing removed at all.
