### ISSUE TITLE
the windows detection code is unreliable.

### ISSUE THREAD

**Issue by divinity76** [alexantr/filemanager#17]
it checks if its windows by checking if the DIRECTORY_SEPARATOR is `\` - unfortunately, at least 4 OSs use \  for directory separator, including Windows, OS/2, eComStation/eCS, and Symbian OS... a more reliable detection would probably be `define('FM_IS_WIN', (false!==(stripos(php_uname('s'),'windows'))));`

**Comment by alexantr** [comment]
Can you run filemanager on OS/2, eComStation/eCS, and Symbian OS?

**Comment by divinity76** [comment]
not `AND`, but `OR` - if it can successfully run on any of these systems, then the bug should be possible to hit. given that PHP 5.6 is ported to eComStation  ( http://os2ports.smedley.id.au/index.php?page=php-5-6 ), i bet it will. i'll run some tests and let you know if i can get it running on eComStation or not

**Comment by alexantr** [comment]
`FM_IS_WIN` is using for hiding owner and perms which not applicable in Windows OS.
AFAIK same behavior is true for other OSs with `\`

**Comment by divinity76** [comment]
huh, that's weird, because windows, since at least Windows NT 3.1 back in 1993, has supported file ownership and permissions, with the introduction of the NTFS filesystem :)

**Comment by alexantr** [comment]
Can you implement management administration of windows ownership and permissions?
Stop! Do not try this, bcs this filemanager created for quick deploy  on linux-based shared hostings and must not use as regular filemanager in production.
