### ISSUE TITLE
[new function] Only working on current folder and all sub folders

### ISSUE THREAD

**Issue by zengXchao** [alexantr/filemanager#22]
Is it possible to set current folder (containing "filemanager.php") as the root path and make this script just working on current and all sub folders ?

**Comment by alexantr** [comment]
Try
```php
$root_path = __DIR__;
$root_url = trim(dirname($_SERVER['PHP_SELF']), '/');
```

**Comment by zengXchao** [comment]
It's working for me! Thanks!
