### ISSUE TITLE
Filemanager and Yii2

### ISSUE THREAD

**Issue by logofakt** [alexantr/filemanager#3]
You may use it in Yii2 like this

In a controller call
public function fileman {
    return $this->render('filemanager')
}

In views put filemanager.php.
At the top of the file put
use yii\helpers\Url;
define('FM_EMBED', true);
define('FM_LANG', 'en');
define('FM_SELF_URL', Url::base());

In your elfinder I created an issue, if you would have a look at it?

**Comment by alexantr** [comment]
One more example without view file:
```php
/**
 * @return mixed
 * @throws ServerErrorHttpException
 */
public function actionFilemanager()
{
    $manager = Yii::getAlias('@app/tools/filemanager.php');
    if (!is_file($manager)) {
        throw new ServerErrorHttpException('"PHP File Manager" not found.');
    }

    Yii::$app->response->format = Response::FORMAT_RAW;

    error_reporting(E_ALL);

    define('FM_EMBED', true);
    define('FM_LANG', 'en');
    define('FM_SELF_URL', Url::canonical());

    ob_start();
    ob_implicit_flush(false);

    require $manager;

    return ob_get_clean();
}
```
I'm using this variant.
