### ISSUE TITLE
it just misses a text editor....

### ISSUE THREAD

**Issue by harmony197** [alexantr/filemanager#33]
thank you for this great file manager
it just misses a text editor for this filemanager to be ultimate..
my english is bad sorry.
harmony

**Comment by ghost** [comment]
Hey, I could try to make a text editor but it might take a while.
When i've finished making it i'll send you my clone of this repo so you can use my remade version.

:)

**Comment by prasathmani** [comment]
@harmony197 try [tinyfilemanager](https://github.com/prasathmani/tinyfilemanager).

**Comment by harmony197** [comment]
great With text editor it is ultimate version thank you
