### ISSUE TITLE
Download folders and modify files

### ISSUE THREAD

**Issue by eArabic** [alexantr/filemanager#4]
Thank you very much for this wonderful script strong.
There are some features are not present which is very necessary in the File Manager.
I noticed that the download is available folders, as well as modify files, for example, php and others are not available.
Is it possible to add these features, and thank you very much, You Greetings
I apologize to the spelling mistakes, I do not know English well

![023](https://cloud.githubusercontent.com/assets/24383546/21502090/60f2c83a-cc5e-11e6-813c-a97fcaeca3da.png)

![024](https://cloud.githubusercontent.com/assets/24383546/21502093/65ecc5a2-cc5e-11e6-9c61-7d88596ca4e3.png)

![025](https://cloud.githubusercontent.com/assets/24383546/21502096/6a8e3eec-cc5e-11e6-97b3-7c86231e28c6.png)

**Comment by eArabic** [comment]
Thank you so much.
If it is added to the folders and files compression  zip  feature, such as the idea that in the picture, thank you very much, I do not know English.

![01010](https://cloud.githubusercontent.com/assets/24383546/21656967/63bc2a2e-d2d1-11e6-96ff-5e76df6a2bdb.png)

![1020](https://cloud.githubusercontent.com/assets/24383546/21656973/689b1f46-d2d1-11e6-9634-98a1f23d1ff3.png)

**Comment by eArabic** [comment]
I am sorry this feature  compression zip I've noticed Available

![aa](https://cloud.githubusercontent.com/assets/24383546/21753183/6284a21a-d5f8-11e6-867d-2946ed42d28c.png)

**Comment by eArabic** [comment]
I do not know what programming is the reason that the filemanager can not get a full permissions and can not change.

![w2](https://cloud.githubusercontent.com/assets/24383546/21753209/166c3be4-d5f9-11e6-8c92-44991ca39853.png)
![2q](https://cloud.githubusercontent.com/assets/24383546/21753210/166e6216-d5f9-11e6-8dad-d48170c055ee.png)

**Comment by eArabic** [comment]
Hello , Thank you very much and have benefited greatly from filemanager
How do you make him open the pages without deleting a section of the title (/var/www/) each time.
It does not open the page directly from the directory where its place

![1](https://cloud.githubusercontent.com/assets/24383546/21759138/0c81d288-d653-11e6-9ebe-02d5bdd2da0a.png)

![2](https://cloud.githubusercontent.com/assets/24383546/21759141/118ad1a8-d653-11e6-8343-2a9b47c0ffd3.png)

**Comment by alexantr** [comment]
Direct links work only with default config when fm root folder is equals web server root folder.

**Comment by eArabic** [comment]
Thank you very much, waiting for download is available folders and modify files it is very important .

**Comment by eArabic** [comment]
Thank you very much, now works very excellent.

![ee](https://cloud.githubusercontent.com/assets/24383546/21759427/43323636-d655-11e6-91b9-e5a5690a2312.png)

![44](https://cloud.githubusercontent.com/assets/24383546/21759430/47343360-d655-11e6-9590-a63ca1dd171a.png)

**Comment by alexantr** [comment]
If you want to edit files please try [tinyfilemanager](https://github.com/prasathmani/tinyfilemanager)
