### ISSUE TITLE
Unzip option?

### ISSUE THREAD

**Issue by Zebam** [alexantr/filemanager#6]
Can you add unzip option to this file manager?

**Comment by alexantr** [comment]
Already done. Go to archive's info page (press on filename) and press "Unpack" or "Unpack to folder".

**Comment by Zebam** [comment]
Thanks. I saw at few mins after posting message.

Any plans for adding file editing options (php, html etc) like other member proposed?

Overall, well done with this script.

**Comment by alexantr** [comment]
Yes. See #4
