### ISSUE TITLE
If we can specify a folder as the init directory of the file management?

### ISSUE THREAD

**Issue by Amamatthew** [alexantr/filemanager#7]
If we can specify a folder as the init directory of the file management shows instead of the folder homepage root folder located. Because sometimes we use this class file as a third party library in the application system.

**Comment by alexantr** [comment]
Please change `$root_path` and `$root_url` or `FM_ROOT_URL` and `FM_SELF_URL` if using as embed library.

Example:
```php
$root_path = $_SERVER['DOCUMENT_ROOT'] . '/foo/bar';
$root_url = 'foo/bar';
```
