### ISSUE TITLE
showing sensitive files like .htaccess

### ISSUE THREAD

**Issue by vvcares** [alexantr/filemanager#9]
Can hide the files ?
showing sensitive files like .htaccess

**Comment by alexantr** [comment]
Yes we can

**Comment by vvcares** [comment]
Please, how to make it?

**Comment by alexantr** [comment]
Please check new release.

**Comment by vvcares** [comment]
Hi alexantr.,
Tested & works perfectly for hidden files. :-)
Thank you for your very very quick responses.

**Comment by C-Duv** [comment]
With `$show_hidden_files = false;` *dot files* are hidden from list of files but still *viewables* using forged URL.
For example to view `.htaccess` file:
http://127.0.0.1/filemanager.php?p=&view=.htaccess

**Comment by alexantr** [comment]
Please create PR

**Comment by alexantr** [comment]
Sorry but this feature will be removed soon.

**Comment by alexantr** [comment]
I removed hiding hidden files.

Please try [tinyfilemanager](https://github.com/prasathmani/tinyfilemanager)
